name: Build test

on:
  workflow_call:

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
              go-version-file: go.mod

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v4
          with:
              version: latest
              args: release --snapshot --clean
