name: Build images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
env:
  IMAGE_NAME: 'scan2html'
  REGISTRY: 'ghcr.io'
  TRIVY_VERSION: ${{ vars.TRIVY_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{env.REGISTRY}}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags:   |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=scan2html
            org.opencontainers.image.description=A Trivy plugin that scans and outputs the results to a html file.
            org.opencontainers.image.vendor=Smartforce

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TRIVY_VERSION=${{ env.TRIVY_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
