name: Test build

on:
    push:
        branches:
            - main
        paths:
            - 'plugin.yaml'
    workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: nikpivkin/gh-test/.github/workflows/simple-build.yaml@main
  
