name: Unit test

on:
  workflow_call:
  
jobs:
  unit-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
              go-version-file: go.mod

        - name: go mod tidy
          run: |
              go mod tidy
              if [ -n "$(git status go.mod --porcelain)" ]; then
                echo "Run 'go mod tidy' and push it"
                exit 1
              fi

        - name: Run unit tests
          run: go test -v ./...
